### ISSUE TITLE
Feature Request: ldap-group based permissions

### ISSUE THREAD

**Issue by alphabet5** [alphabet5/guacamole-compose#17]
Ability to assign permissions based on the ldap group. 

Users would have access to the connections that are in the same group. Alternatively - permissions for a specific connection could be determined by the users permissions on that machine - granted if they have Remote Desktop privileges, or denied if they don't.

I'm currently thinking of something like this.

```yaml
ldap_groups:
  default:
    ldap_server: domain.com
    ldap_user: guac_user
    ldap_password: password
    ldap_domain: domain.com
  group1:
    ldap_group: guacamole
  group2:
    ldap_group: guacamole_restricted
  different-domain:
    ldap_server: domain2.com
    ldap_user: guac_user
    ldap_password: password
    ldap_domain: domain2.com
```

Things that need to be figured out yet:

- How users in multiple groups will be handled.
- How connections will be handled if there ends up being a computer in multiple groups.
- How default connection settings should change based on the ldap group domain.
- Updating user permissions.
- Manually defined connection permissions.
- Ability to override connection permissions in parameters.yaml?
- Mechanism of fetching permissions from each connection.

There have been a couple of instances where this could be helpful. It would also help with users to reduce confusion when the user doesn't have Remote Desktop privileges on a connection that they have 'permission' to access through guacamole.
